Repository arduino-libraries/WiFiNINA, pull requests merged in 2025-03, with the labels that each got.

#284 Preferences api introduction
  .github/workflows/compile-examples.yml
  examples/PreferencesCounter/PreferencesCounter.ino
  examples/PreferencesValidation/PreferencesValidation.ino
  examples/PreferencesValidation/test.h
  examples/Prefs2Struct/Prefs2Struct.ino
  src/WiFiPreferences.cpp
  src/WiFiPreferences.h
  src/utility/spi_drv.cpp
  src/utility/spi_drv.h
  src/utility/wifi_drv.cpp
  src/utility/wifi_drv.h
  src/utility/wifi_spi.h
Labels: type: enhancement, topic: code, 2.x.x

#292 Add command to override BearSSL TrustAnchor
  src/WiFiClient.cpp
  src/WiFiClient.h
  src/WiFiSSLClient.cpp
  src/WiFiSSLClient.h
  src/utility/server_drv.cpp
  src/utility/server_drv.h
  src/utility/wifi_spi.h
Labels: type: enhancement, topic: code, 2.x.x

#293 Add command to read BearSSL client errorCode
  src/WiFiClient.cpp
  src/WiFiClient.h
  src/WiFiSSLClient.cpp
  src/WiFiSSLClient.h
  src/utility/server_drv.cpp
  src/utility/server_drv.h
  src/utility/wifi_spi.h
Labels: type: enhancement, topic: code, 2.x.x

#294 Add command to set nina-fw system time
  src/WiFi.cpp
  src/WiFi.h
  src/utility/wifi_drv.cpp
  src/utility/wifi_drv.h
  src/utility/wifi_spi.h
Labels: type: enhancement, topic: code

#254 WiFiServer - added end(), begin(port) and ctor without parameters
  docs/api.md
  src/WiFiServer.cpp
  src/WiFiServer.h
  src/utility/server_drv.cpp
  src/utility/server_drv.h
  src/utility/wifi_spi.h
Labels: type: enhancement, topic: code

#252 WiFiClient connect timeout
  docs/api.md
  src/WiFiClient.cpp
  src/WiFiClient.h
  src/utility/server_drv.cpp
  src/utility/server_drv.h
Labels: type: enhancement, topic: code

#205 WiFiPagerServer example to better show how server.available() and server.print() work
  examples/WiFiPagerServer/WiFiPagerServer.ino
  examples/WiFiPagerServer/arduino_secrets.h
Labels: type: enhancement, topic: documentation

#219 WiFi.config - setting defaults as the Ethernet library
  src/WiFi.cpp
Labels: topic: code
